allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@kitschpatrol/cspell-config@8.12.1'
  - '@kitschpatrol/eslint-config@8.12.1'
  - '@kitschpatrol/knip-config@8.12.1'
  - '@kitschpatrol/mdat-config@8.12.1'
  - '@kitschpatrol/prettier-config@8.12.1'
  - '@kitschpatrol/remark-config@8.12.1'
  - '@kitschpatrol/repo-config@8.12.1'
  - '@kitschpatrol/safe-stable-stringify@2.5.0-fork.2'
  - '@kitschpatrol/shared-config@8.12.1'
  - '@kitschpatrol/stylelint-config@8.12.1'
  - '@kitschpatrol/typescript-config@8.12.1'
  - lognow@0.8.5
  - mdat@3.6.2
  - metascope@0.12.2
  - read-pyproject@0.4.1
  - remark-mdat@3.1.1
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
